package.json
NodeJS types of version 8, 10 and 12 are not compatible and alongside cause type errors. If one of dependencies in dependency tree requires specific NodeJS type version, then most likely the project will end up with two (or more) NodeJS types. Therefore if you support any NodeJS version then also require any of NodeJS type versions, using `*`, `>= 8`, or what's more appropriate.
=> fix: dependencies for node types of any version

README.md, src/GetResponseType.ts, src/GetResponseTypeFromEndpointMethod.ts, src/index.ts
=> feat: `GetResponseTypeFromEndpointMethod` and `GetResponseDataTypeFromEndpointMethod` helpers

package.json
Prevents #40 from happening again
=> test: run `tsc` with `--noImplicitAny` flag

README.md, package.json, scripts/update-endpoints/templates/endpoints.ts.template, src/EndpointInterface.ts, src/RequestInterface.ts, src/RequestParameters.ts, src/generated/Endpoints.ts, test.ts
Defaults from `.endpoint.defaults(options)` and `.request.defaults(options)` are now passed on.
For example, before
```ts
import { EndpointInterface } from "@octokit/types";
const endpoint = null as EndpointInterface;
const fooOptions = { foo: "bar" };
endpoint.defaults(fooOptions).DEFAULTS.foo;
// type: any
```
after
```ts
import { EndpointInterface } from "@octokit/types";
const endpoint = null as EndpointInterface;
const fooOptions = { foo: "bar" };
endpoint.defaults(fooOptions).DEFAULTS.foo;
// type: string
```
=> Add optional defaults type parameter to EndpointInterface & RequestInterface

scripts/update-endpoints/typescript.js, src/generated/Endpoints.ts
This adds a workaround in typescript.js to override the data parameter
type for ReposUploadReleaseAssetEndpoint. The endpoint type from the
openapi graphql server only specifies  string as a type, when it can
take a string or a Buffer.
Closes #73
=> types: add workaround for uploadReleaseAsset

scripts/update-endpoints/templates/endpoints.ts.template, src/generated/Endpoints.ts, test.ts
=> fix: response.data type should not  be unknown if endpoint has both `20x` and `301`/`302` response types

package-lock.json, package.json
see https://github.com/jabuco/pika-plugin-merge-properties/issues/2 on why we set properties to an object instead of an array
=> fix: set `"octokit"` key on published package

scripts/update-endpoints/templates/endpoints.ts.template, src/generated/Endpoints.ts
fixes #254. I confirmed locally that it fixes https://github.com/octokit/request.js/pull/352
=> fix: `Endpoints["PUT /user/starred/{owner}/{repo}"]["response"]` returns `OctocitResponse` type

package-lock.json, package.json, src/RequestRequestOptions.ts
This will help us with making Octokit work with Deno via skypack. See https://github.com/skypackjs/skypack-cdn/issues/134
=> fix: remove dependency on "http" types

scripts/update-endpoints/templates/endpoints.ts.template, src/generated/Endpoints.ts
=> fix: `POST /repos/{owner}/{repo}/forks` has a `never` response type

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update.yml
Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾
=> ci(workflow): add cache to workflows using actions/setup-node

package-lock.json, package.json
`@octokit/openapi-types` v9 changed all component keys with `_` to use `-`. `@octokit/types` is not exposing these properties to a fix release is enough
=> fix(deps): bump `@octokit/openapi-types` to v9

package-lock.json, package.json
- build(deps): bump `@octokit/openapi-types` to `^9.1.0`
- build(package): lock file
=> feat: `GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs` and `GET /repos/{owner}/{repo}/actions/runs` now have a `created` parameter

package-lock.json, package.json
- fix(deps): bump `@octokit/types` to `^9.1.1`
- build(package): lock file
=> fix: `POST /repos/{owner}/{repo}/releases/{release_id}/assets`: `name` query parameter is required. `head.repo` is nullable in `pull-request` schema

src/RequestInterface.ts
This PR attempts to address https://github.com/octokit/core.js/issues/469 (route auto suggestion is not triggered).
The request definition was split to two overloads: one for known routes (`keyof Endpoints`) and another one for "catch all" `Route` (any `string`)
The autocomplete stopped working in Typescript 4.7, but I couldn't find anything related in release notes.
---
Closes https://github.com/octokit/core.js/issues/469
=> fix(RequestInterface): make types with VS Code Typeahead and TypeScript 4.7

package-lock.json, package.json
Reverts octokit/types.ts#467
This seems to have broken the "update" process because it's an ES module and we're using `require`. We can fix that at some point, but for now, let's revert.
=> fix(deps): revert upgrade of dependency `sort-keys` to v5

package.json
I was on my Windows 10 machine going down the rabbit hole of GH OpenAPI spec typedefs and realized that the lint (prettier) functionality doesn't work on Windows machines for this repository.
My first thought was that it was broken all around but on non-Windows machines I realized it was working!
I have not created an issue for this as I had already figured it out before getting to the point of PR creation.  If you'd like me to create an issue and link it to this PR just let me know.
----
Changing the prettier files list being wrapped with single quotes to escaped double quotes.  Before it would not find any files, which afterwards [I found seems to catch others as well](https://github.com/prettier/prettier/issues/4086#issuecomment-370228517).
```
$ npm run lint
> …
```
=> build: npm lint to properly find files on Win OS

scripts/update-endpoints/fetch-json.js, scripts/update-endpoints/generated/endpoints.json, scripts/update-endpoints/templates/endpoints.ts.template, scripts/update-endpoints/typescript.js, src/AuthInterface.ts, src/EndpointDefaults.ts, src/EndpointInterface.ts, src/RequestHeaders.ts, src/RequestInterface.ts, src/RequestParameters.ts, src/generated/Endpoints.ts
Followup to https://github.com/octokit/endpoint.js/pull/382#issuecomment-1370197900
See also https://github.com/octokit/endpoint.js/pull/388 https://github.com/octokit/core.js/pull/538 https://github.com/octokit/plugin-paginate-rest.js/pull/486
----
* Previews were documented
* Previews are no longer documented
* This PR must be merged before all other ones in the Octokit JS repos
----
If `Yes`, what's the impact:  
* Removal of previews
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: …
=> feat: remove previews

scripts/update-endpoints/fetch-json.js, scripts/update-endpoints/generated/endpoints.json, scripts/update-endpoints/templates/endpoints.ts.template, scripts/update-endpoints/typescript.js, src/AuthInterface.ts, src/EndpointDefaults.ts, src/EndpointInterface.ts, src/RequestHeaders.ts, src/RequestInterface.ts, src/RequestParameters.ts, src/generated/Endpoints.ts
This reverts commit cb0835bc8a8c47bacdd361a793fce0fb197a12bc.
This reverts #491 because removing the previews logic broke the build for our enterprise modules such as plugin-enterprise-server.js, because of old versions of GHE such as v3.2 and v3.3 (set to be deprecated next week).   
Also, because GraaphQL previews are not deprecated yet @octokit/core, @octokit/graphql, and octokit.js will need to be modified. 
I missed these things in my review, which is why I am reverting this changeset; so that we can modify the other libraries first and then remove this logic.
----
* Previews logic was removed
* Previews logic has been reintroduced.
----
If `Yes`, what's the impact:
* N/A
----
=> Revert "feat: remove previews (#491)"

package-lock.json, package.json
The `sort-keys` dependency switched to ESM and is thus incompatible
Resolves #496
----
* The automated updates workflows was failing
* The automated update workflow should now run properly
*
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----
=> build(deps): downgrade `sort-keys` to v4

scripts/update-endpoints/templates/endpoints.ts.template, src/generated/Endpoints.ts
This doesn't affect the parameters themselves
Resolves #554
----
* Since the parameter types could be potentially undefined, the type could return `never`
* The type now removes the potentially undefined type and it no longer returns `never`
*
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
----
=> fix: remove all potentially undefined parameter types

package-lock.json, package.json
This should unblock updates in https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/687 and https://github.com/octokit/plugin-paginate-rest.js/pull/569.
=> fix: bump the version of @octokit/openapi-types to v19.0.1

src/OctokitResponse.ts
Resolves #ISSUE_NUMBER
Required for https://github.com/octokit/plugin-throttling.js/pull/642
----
* Plugins could not define additional properties on the response object
* Allows plugins to extend the response object types by using declaration merging, required in `@octokit/plugin-throttling` due to https://github.com/octokit/plugin-throttling.js/pull/539
----
=> feat(types): make `OctokitResponse` an interface

scripts/update-endpoints/templates/endpoints.ts.template, src/generated/Endpoints.ts
Backports some improvements from `@octokit-next`:
- Simplify (flatten) the parameters
- Add type support for 205 HTTP status code
- Add types for the `data` parameter
Resolves #ISSUE_NUMBER
----
* 
* 
----
=> feat: backport improvements from `@octokit-next`

src/ResponseHeaders.ts
https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#resource-not-accessible
Resolves #607
----
* `x-accepted-github-permissions` header isn't exposed
* `x-accepted-github-permissions` will hopefully be exposed
----
=> feat: add x-accepted-github-permissions

src/RequestRequestOptions.ts
----
* The `redirect` option was removed from `@octokit/request` v8
* Adds the `redirect` option, and moves it to `RequestRequestOptions`
----
=> feat: add `redirect` option in `RequestRequestOptions`

package.json, tsconfig.json
Compatibility was accidentally removed from this package in https://github.com/octokit/types.ts/commit/a3a96043f3efc81a9ea3601bc8261e2877de94dd
Typescript falsely reports that this package isn't compatible with CJS when it is. This package contains no runtime code and only types.
This is due to adding `"type": "module"` to the `package.json` in order to fix some type issues introduced by upgrading `@octokit/tsconfig`
Fixes octokit/types.ts#650
=> fix: restore CJS compat

package-lock.json, package.json, tsconfig.json
See https://github.com/octokit/octokit.js/issues/2762#issuecomment-2486997620
Resolves #ISSUE_NUMBER
----
* Types would include a reference to `@types/node` even though there is nothing using Node specific APIs in the types
* Remove dependency on `@types/node` to make sure types are platform agnostic
----
=> fix: remove `@types/node` from generated types

.github/workflows/release.yml
Resolves #613
----
* release.yml fails on forks
* release.yml won't fail on forks
----
=> Fix release.yml by only running for octokit owner

src/RequestParameters.ts
Resolves #406
Requires https://github.com/octokit/graphql.js/pull/629 to be merged
----
* `operationName` and `query` is not documented by types 🚫 
* `operationName` and `query` is documented by types ✅ 
----
=> feat(GraphQL): add type documentation for `query` and `operationName`
